/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Producto;
import persistencia.Conexion;

/**
 *
 * @author Diurno
 */
public class ActualizarPrecio extends javax.swing.JFrame {

    Conexion con = new Conexion();
    ArrayList<Producto> productos = new ArrayList<>();
    
    /**
     * Creates new form ActualizarPrecio
     */
    public ActualizarPrecio() {
        initComponents();
        cargarDatos();
    }

    public void cargarDatos(){ 
        productos=con.sacarIdProductos();
        for (Producto producto : productos) {
            String a = String.valueOf(producto.getNombre());
            cmBoxProductos.addItem(a);
        }
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmBoxProductos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblPrecioActual = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNuevoPrecio = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(480, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("Actualizar Precio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 19, -1, -1));

        jLabel2.setText("Seleccione el producto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 83, -1, -1));

        cmBoxProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmBoxProductosActionPerformed(evt);
            }
        });
        getContentPane().add(cmBoxProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jLabel3.setText("Precio actual:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        lblPrecioActual.setText("00.00");
        getContentPane().add(lblPrecioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 40, 20));

        jLabel4.setText("Nuevo Precio:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 156, -1, -1));
        getContentPane().add(txtNuevoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 153, 85, -1));

        btnVolver.setText("Volver al menú");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        new MenuCompraProveedor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        try{
            String producto = cmBoxProductos.getSelectedItem().toString();
            double nuevoPrecio = Double.parseDouble(txtNuevoPrecio.getText());
            con.actualizarPrecioProducto(producto, nuevoPrecio);
            
            JOptionPane.showMessageDialog(null, "Nuevo Precio actualizado correctamente.");
            
            new ActualizarPrecio().setVisible(true);
            this.dispose();
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Error al leer el Nuevo Precio.");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void cmBoxProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmBoxProductosActionPerformed
        // TODO add your handling code here:
        for (Producto producto : productos) {
            String a = String.valueOf(producto.getNombre());
            if(cmBoxProductos.getSelectedItem().equals(a)){
                lblPrecioActual.setText(String.valueOf(producto.getPrecio()));
                
            }
        }
    }//GEN-LAST:event_cmBoxProductosActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ActualizarPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ActualizarPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ActualizarPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ActualizarPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ActualizarPrecio().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmBoxProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblPrecioActual;
    private javax.swing.JTextField txtNuevoPrecio;
    // End of variables declaration//GEN-END:variables
}
