/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import modelo.Compra;
import modelo.CompraDetalleView;
import modelo.Proveedor;
import persistencia.Conexion;
//import vista.MenuCompraProveedor;

/**
 *
 * @author Diurno
 */
public class Consultar extends javax.swing.JFrame {

    DefaultTableModel modelo;
    Conexion con = new Conexion();
    ArrayList<Proveedor> proveedores = new ArrayList<>();
    ArrayList<Compra> compras = new ArrayList<>();
    ArrayList<CompraDetalleView> viewCompras = new ArrayList<>();
    
    /**
     * Creates new form Consultar
     */
    public Consultar() {
        initComponents();
        modelo = (DefaultTableModel) jTable1.getModel();
        
        modelo.setRowCount(0);
        
        cargarDatos();
        /*if(cmBoxProvedores.getSelectedItem().equals("Ninguno")){
            for (DetalleCompra detalle : controlador.consultarCompraPorProveedor()) {
                Object[] fila = { empleado.getId(), empleado.getApellido(), empleado.getOficio(), empleado.getLoc()};
                modelo.addRow(fila);
            }
        }*/
    }
    
    public void cargarDatos(){
        proveedores = con.obtenerProveedores();
        for (Proveedor proveedor : proveedores) {
            cmBoxProvedores.addItem(proveedor.getNombre());
        }
        
        compras = con.sacarFechas();
        for (Compra compra : compras) {
            cmBoxFechas.addItem(compra.getFechaString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmBoxProvedores = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmBoxFechas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnFecha = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("Consultar Compras por:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 210, 20));

        jLabel2.setText("Proveedor :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        getContentPane().add(cmBoxProvedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setText("Fecha :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        cmBoxFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmBoxFechasActionPerformed(evt);
            }
        });
        getContentPane().add(cmBoxFechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID COMPRA", "ID PROVEEDOR", "PRODUCTO", "CANTIDAD", "PRECIO", "FECHA"
            }
        ));
        jTable1.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, 250));

        btnVolver.setText("Volver al menú");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        btnProveedor.setText("Buscar Proveedor");
        btnProveedor.setActionCommand("");
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, 30));

        btnFecha.setText("Buscar Fecha");
        btnFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 140, 30));

        jButton1.setText("Buscar Fecha y Pro.");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 140, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        new MenuCompraProveedor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cmBoxFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmBoxFechasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmBoxFechasActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        // TODO add your handling code here:
        viewCompras.clear();
        modelo.setRowCount(0);
        
        int id_proveedor=0;
        for (Proveedor proveedor : proveedores) {
            if(proveedor.getNombre().equals( cmBoxProvedores.getSelectedItem())){
                id_proveedor=proveedor.getIdProveedor();
            }
        }

        viewCompras = con.consultarCompraPorProveedor(id_proveedor);
        
        for (CompraDetalleView viewCompra : viewCompras) {
            Object[] fila = {viewCompra.getId_compra(),viewCompra.getId_proveedor(),viewCompra.getId_producto(),viewCompra.getCantidad(),viewCompra.getPrecio(),viewCompra.getFechaString()};
            modelo.addRow(fila);
        }
        
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaActionPerformed
        // TODO add your handling code here:
        viewCompras.clear();
        modelo.setRowCount(0);
        Date fechaBuscada = null;
        for (Compra compra : compras) {
            if(compra.getFechaString().equals(cmBoxFechas.getSelectedItem())){
                fechaBuscada= compra.getFecha();
            }
        }
        
        viewCompras = con.consultarCompraPorFecha(fechaBuscada);
        
        for (CompraDetalleView viewCompra : viewCompras) {
            Object[] fila = {viewCompra.getId_compra(),viewCompra.getId_proveedor(),viewCompra.getId_producto(),viewCompra.getCantidad(),viewCompra.getPrecio(),viewCompra.getFechaString()};
            modelo.addRow(fila);
        }
    }//GEN-LAST:event_btnFechaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        viewCompras.clear();
        modelo.setRowCount(0);
        Date fechaBuscada = null;
        for (Compra compra : compras) {
            if(compra.getFechaString().equals(cmBoxFechas.getSelectedItem())){
                fechaBuscada= compra.getFecha();
            }
        }
        
        int id_proveedor=0;
        for (Proveedor proveedor : proveedores) {
            if(proveedor.getNombre().equals( cmBoxProvedores.getSelectedItem())){
                id_proveedor=proveedor.getIdProveedor();
            }
        }
        
        viewCompras = con.consultarCompraPorProveedoryFecha(id_proveedor, fechaBuscada);
        
        for (CompraDetalleView viewCompra : viewCompras) {
            Object[] fila = {viewCompra.getId_compra(),viewCompra.getId_proveedor(),viewCompra.getId_producto(),viewCompra.getCantidad(),viewCompra.getPrecio(),viewCompra.getFechaString()};
            modelo.addRow(fila);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Consultar().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFecha;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmBoxFechas;
    private javax.swing.JComboBox<String> cmBoxProvedores;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
       
}
